# Generated by Django 4.2.14 on 2024-08-15 09:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_sold_quantity_species'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherhistory',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name='created at'),
            preserve_default=False,
        ),
    ]
