# Generated by Django 4.2.15 on 2024-08-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_voucherhistory_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='size',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('S', 'S'), ('XS', 'XS'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=255, null=True, verbose_name='size'),
        ),
    ]
