# Generated by Django 4.2.15 on 2024-08-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_bill_is_deleted_billdetail_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_deleted',
            field=models.BooleanField(
                default=False,
                verbose_name='is deleted'),
        ),
    ]
