from django.urls import path, include
from .views import *

urlpatterns = [
    path(
        '',
        index,
        name='index'),
    path(
        'shop/',
        ShopView,
        name='shop'),
    path(
        'sign-in/',
        login_view,
        name="sign-in"),
    path(
        'sign-up/',
        signup_view,
        name="sign-up"),
    path(
        '',
        include('django.contrib.auth.urls')),
    path(
        'product/<int:id>/',
        product_detail_view,
        name='product_detail'),
    path(
        'get-price/',
        get_price,
        name='get_price'),
    path(
        'get-available-options/',
        get_available_options,
        name='get_available_options'),
    path(
        'get-product-detail-id/',
        get_product_detail_id,
        name='get_product_detail_id'),
    path(
        'add-to-cart/',
        add_to_cart,
        name='add_to_cart'),
    path(
        'cart/',
        cart_view,
        name='cart'),
    path(
        'update-quantity/',
        update_quantity,
        name='update_quantity'),
    path(
        'remove_from_cart/<int:item_id>/',
        remove_from_cart,
        name='remove_from_cart'),
    path(
        'verify-input/',
        verify_input,
        name="verify-input"),
    path(
        'search-products/',
        search_products,
        name='search_products'),
    path(
        'vouchers/',
        voucher_list,
        name='voucher_list'),
    path(
        'profile/<int:pk>/',
        profile_view,
        name='profile'),
]
